DROP TABLE IF EXISTS HITS CASCADE;

CREATE TABLE IF NOT EXISTS HITS (
  HIT_ID    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY    NOT NULL,
  APP       VARCHAR(255)                                        NOT NULL,
  URI       VARCHAR(512)                                        NOT NULL,
  IP        VARCHAR(16)                                         NOT NULL,
  CREATED   TIMESTAMP WITHOUT TIME ZONE                       NOT NULL
);